spring.application.name=api-gateway
server.port=8087

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Delivery_Board_Realm