server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /openapi.yaml {
        root /usr/share/nginx/html;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type' always;
    }

    location = /index.html {
        root /usr/share/nginx/html;
        expires -1;
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, max-age=0';
    }
}
