spring.application.name=EVENEMENT-SERVICE

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

# Local fallback when the Config Server is unavailable
server.port=8082

spring.datasource.url=jdbc:h2:mem:evenementdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,env,refresh
management.endpoint.health.show-details=always

evenement.message=Configuration locale de secours pour EVENEMENT-SERVICE

# Force-disable servlet security in this MS (security is handled by API Gateway)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
